---
title: "DSAN 5200: Advanced Data Visualization"
subtitle: "Section 03, Tuesdays, 12:30-3pm, Car Barn 309"
author: "Jeff Jacobs, <a href='mailto:jj1088@georgetown.edu' target='_blank'>`jj1088@georgetown.edu`</a>"
institute: "Georgetown University, Spring 2024"
---

{{< include _draft-notice.qmd >}}

DSAN 5200: Advanced Data Visualization, Georgetown University, Spring 2024. Tuesday, 12:30pm-3:00pm, Car Barn 309.

**Course Description:**

Presenting quantitative information in visual form is an essential communication skill for data professionals. This course introduces representation methods and visualization techniques for complex data, drawing on insights from cognitive science and graphic design. Students will obtain an overview of the human visual system, learn to use models for data and for images, and acquire good design practices, such as those using the “grammar of graphics.” Students will use common statistical design tools such as graphic methods in Python3, interactive graphic methods such as Bokeh, Leaflet, and NetworkD3, the R package ggplot2, and Tableau. *Prerequisites: DSAN 5000. 3 credits.*
