---
title: "Week 1: Course Intro and Data Science Toolbox"
subtitle: "*DSAN 5200: Advanced Data Visualization*<br>Section 03 (Tues 12:30-3pm)"
author: "Jeff Jacobs"
institute: "<a href='mailto:jj1088@georgetown.edu' target='_blank'>`jj1088@georgetown.edu`</a>"
date: 2024-01-16
date-format: full
format:
  revealjs:
    df-print: kable
    output-file: slides.html
    theme: ["../_jjslides.scss"]
    footer: "DSAN 5200-03 Week 1: Course Intro and Toolbox"
    echo: true
    code-fold: show
    scrollable: true
    slide-number: true
    html-math-method: mathjax
    include-in-header:
      text: "<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css' integrity='sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65' crossorigin='anonymous'><link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css'>"
    simplemenu:
      flat: true
      barhtml:
        header: "<div class='menubar'><span style='position: absolute; left: 8; padding-left: 8px;'><a href='./index.html'>&larr; Return to Notes</a></span><ul class='menu'></ul></div>"
      scale: 0.5
    revealjs-plugins:
      - simplemenu
  html:
    df-print: kable
    output-file: "index.html"
    echo: true
    code-fold: show
    html-math-method: mathjax
---

::: {.content-visible unless-format="revealjs"}

{{< include ../_draft-notice.qmd >}}

<center>
<a class="h2" href="./slides.html" target="_blank">Open slides in new window &rarr;</a>
</center>

:::

# Schedule {data-name="Schedule"}

```{=html}
<table>
<thead>
<tr>
    <th>Start</th>
    <th>End</th>
    <th>Topic</th>
</tr>
</thead>
<tbody>
<tr>
    <td>12:30pm</td>
    <td>1:00pm</td>
    <td><a href='#course-intro'>Course Intro &rarr;</span></a></td>
</tr>
<tr>
    <td>1:00pm</td>
    <td>2:00pm</td>
    <td><a href='#your-data-science-toolbox'>Data Science Toolbox &rarr;</a></td>
</tr>
<tr>
    <td>2:00pm</td>
    <td>2:10pm</td>
    <td>Break!</td>
</tr>
<tr>
    <td>2:10pm</td>
    <td>3:00pm</td>
    <td><a href='#data-visualization-lab'>Data Viz Lab &rarr;</a></td>
</tr>
</tbody>
</table>
```

# Course Intro {data-stack-name="Course Intro"}

## Objectives

* **Think critically** about data and its visual representations
* Distinguish between visualization for data **exploration** vs. **presentation**
* Manipulate/arrange/transform different kinds of data into forms conducive to visualization
* Evaluate **purposes** and **audiences** for your visualizations
* Explore how viz **fits into** larger rubric of data science
* Develop both **static** and **dynamic** visualizations
* Become comfortable with **tools** enabling all of the above

# Your Data Science Toolbox {data-stack-name="Toolbox"}

## Key Tools

* Git
* GitHub
* R and `ggplot2`
* Python
* D3.js

# Data Visualization Lab {data-stack-name="Lab"}

## Our First Visualization Adventure!

